# Generated by Django 6.0.2 on 2026-03-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_name_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_kk",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
